/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class ConstNotionalCrossCurrencyBasisSwapRateHelper extends RateHelper {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ConstNotionalCrossCurrencyBasisSwapRateHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ConstNotionalCrossCurrencyBasisSwapRateHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConstNotionalCrossCurrencyBasisSwapRateHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ConstNotionalCrossCurrencyBasisSwapRateHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ConstNotionalCrossCurrencyBasisSwapRateHelper(QuoteHandle basis, Period tenor, long fixingDays, Calendar calendar, BusinessDayConvention convention, boolean endOfMonth, IborIndex baseCurrencyIndex, IborIndex quoteCurrencyIndex, YieldTermStructureHandle collateralCurve, boolean isFxBaseCurrencyCollateralCurrency, boolean isBasisOnFxBaseCurrencyLeg) {
    this(QuantLibJNI.new_ConstNotionalCrossCurrencyBasisSwapRateHelper(QuoteHandle.getCPtr(basis), basis, Period.getCPtr(tenor), tenor, fixingDays, Calendar.getCPtr(calendar), calendar, convention.swigValue(), endOfMonth, IborIndex.getCPtr(baseCurrencyIndex), baseCurrencyIndex, IborIndex.getCPtr(quoteCurrencyIndex), quoteCurrencyIndex, YieldTermStructureHandle.getCPtr(collateralCurve), collateralCurve, isFxBaseCurrencyCollateralCurrency, isBasisOnFxBaseCurrencyLeg), true);
  }

}
