/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class SplineLogCubic {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SplineLogCubic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SplineLogCubic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_SplineLogCubic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SplineLogCubic() {
    this(QuantLibJNI.new_SplineLogCubic(), true);
  }

}
