/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class SvenssonFitting extends FittingMethod {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SvenssonFitting(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SvenssonFitting_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SvenssonFitting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SvenssonFitting(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SvenssonFitting(Array weights) {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_0(Array.getCPtr(weights), weights), true);
  }

  public SvenssonFitting() {
    this(QuantLibJNI.new_SvenssonFitting__SWIG_1(), true);
  }

}
